### ISSUE TITLE
Kernel source does not match binaries provided on udoo.org

### ISSUE THREAD

**Issue by ghost** [UDOOboard/Kernel_Unico#2]
Hi guys,
The source here is older than the binaries (and presumably the source used to build them) on http://www.udoo.org/downloads/#tab2

Can you please push the updated source?

**Comment by UDOOboard** [comment]
This kernel source is up-to-date, as well as the binaries or the images.

**Comment by ogryb** [comment]
In my binary distro I didn't find kernel config and external symbol files. The /boot directory contains the only uImage file. I've checked /usr/src/linux and /lib/modules/3.0.35 directories, but it's not there either. There are broken links to /home/udoo directory that doesn't exist in the binary distribution.

Please let me know where/how I can download all that. I need it to build additional loadable kernel modules.

Thanks!

**Comment by ogryb** [comment]
@UDOOboard, please take a look at my qs above. I need to compile a loadable kernel module and need the '.config' and Mudules.symvers files for that. Re-compiling the whole kernel is not a desirable option for me, because I don't know what options I should enable in kernel's ".config" and it will take too long.

Is there any reason why you didn't provide kernel's config and external symbols? In all traditional Linux distros it could be usually found in the /boot folder.

Appreciate your help.
